### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by adamdyson** [ANXS/ntp#4]
I've tried overriding the `ntp_timezone` variable in my playbook, so it would be set to Australia/Melbourne however there's no change. Then when I had a look through your source code, I didn't see anything referencing the `ntp_timezone` variable or any attempt to set the correct time zone??

```
- name: Set the correct timezone.
  file:
    src: "/usr/share/zoneinfo/{{ ntp_timezone }}"
    dest: /etc/localtime
    state: link
    force: yes
```
